version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - commerce-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongo:27017/
    depends_on:
      - mongo
    networks:
      - commerce-network          

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ozgebuyuktorun}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - commerce-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-key-here}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./app:/usr/src/ecommerce-app
      - /usr/src/ecommerce-app/node_modules
    networks:
      - commerce-network

  nest-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://ozgebuyuktorun@localhost:5432/ecommerce}
      NODE_ENV: development
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/ecommerce-app
      - /usr/src/ecommerce-app/node_modules
    networks:
      - commerce-network

networks:
  commerce-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  mongo-data:
  node_modules: