version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PGADMIN_PORT}:5050"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - commerce-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - commerce-network

  nest-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/ecommerce-app
      - /usr/src/ecommerce-app/node_modules
    networks:
      - commerce-network

networks:
  commerce-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: